<a href="https://colab.research.google.com/github/diecilyngonzales/Lab-Activities-for-Linear-Algebra-58051/blob/main/Week%208/LinAlg_58051_Matrix_Algebra_Gonzales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
 
class Matrix(list):
  #inherit properties of list
  def __init__(self, matrix):
    self.matrix = matrix
    self.Matrix_Check()
    row = len(matrix)
    self.row = row
    column = len(matrix[0])
    self.column = column
    self.MatrixShape = (row, column) 
 
  def Matrix_Check(self):
    #This checks if the input received by matrix parameter 
    #is indeed an eligible matrix of any dimensions.
    if isinstance(self, list):  
      if any(isinstance(self[x], list) for x in self):
        if any(type(self[x]) != list for x in self):
          raise ValueError("At least one value is not a list") 
        else:
          if any(len(self[x]) != self.column for x in self):
            raise ValueError("Inconsistent matrix width") 
          else:
            return None
      else:
        return None
    else:
      raise ValueError("The input parameter only accepts lists and nested lists") 
 
  def MatrixTranspose(self):
    Row = self.column
    Column = self.row
    TransposedMatrix = []
    #Append the TransposedMatrix with the column values of the first row as a list. 
    #We'll call the newly appended lists as New Row Values.
    #Then, append the New Row Values with the column values of the succeeding rows.
    #Continue until all rows are iterated.
    for i in range(self.row):
      for j in range(self.column):
        if i == 0:
          TransposedMatrix.append([self.matrix[i][j]])
        else:
          TransposedMatrix[j].append(self.matrix[i][j])
    return TransposedMatrix
 
  def Dot(self, Matrix2):
    #Inner product of two square matrix
    if not self.column == Matrix2.row:
      raise ValueError("The dimensions of the two matrices are different")
    Resultant = []
    Matrix1 = self.matrix
    for i_1 in range(self.row):
      for j_2 in range(Matrix2.column):
        j_1 = 0
        i_2 = 0
        Total = 0
        while j_1 != self.column:
          Total += Matrix1[i_1][j_1] * Matrix2.M_index(i_2, j_2)
          i_2 += 1
          j_1 += 1
 
        if j_2 == 0:
          Resultant.append([Total])
        else:
          Resultant[i_1].append(Total)
    return Resultant
 
  def M_index(self, i, j):
    #This is to access a matrix element of another matrix object different from self.matrix
    return self.matrix[i][j]
 
  def M_det(self):
    #This is to acquire the determinant of a square matrix
    #This makes use of calculating the minors
    if self.row != self.column:
      raise ValueError("The matrix input is not a square matrix")
    row, column = self.row, self.column
    if row < 1:
      #If the matrix is null, the determinant is 0
      return 0
    elif row == 1:
      #If the matrix is composed of only 1 element, the determinant is the element itself
      return self.matrix[0][0]
    elif row == 2:
      #If the matrix is a 2 x 2 matrix, the determinant can be acquired using cofactors method
      return self.matrix[0][0] * self.matrix[1][1] - self.matrix[1][0] * self.matrix[0][1]
    else:
      #For matrix with higher dimensions, row echelon will be used to acquire the determinant
      #The final result will be a upper triangular matrix, wherein the determinant will be computed by acquiring the product of the elements of the diagonals.
      #The procedure is as follows:
      ##Check if the matrix is composed of any single row or column with only zeros. If there exists, the determinant of the matrix is zero.
      for i in range(row):
        for j in range(column):
          if self.matrix[i][j] != 0:
            break
            #breaks out of the inner loop only
          if j == max(range(column)):
            return 0
            #This will only be executed if all row values are zero, down to the last element
            #This then returns a determinant of zero
      for j in range(column):
        for i in range(row):
          if self.matrix[i][j] != 0:
            break
            #breaks out of the inner loop only
          if i == max(range(row)):
            return 0
            #This will only be executed if all column values are zero, down to the last element
            #This then returns a determinant of zero
 
      #This will loop up to the second to the last diagonal of the matrix
      ##First, use the current row as pivot row
      ##Then, check if the diagonal in that row is zero (0)
      ##If yes, do next sub-steps. Otherwise, Proceed to next step.
      ### Find a way to swap rows with a non-zero element in the same column as the diagonal of the pivot.
      ### Once found, switch rows. If not, do a similar procedure - but now for the objective of switching columns
      ### If no candidate rows or columns was found, return determinant as 0.
      ##Use the pivot to reduce the other elements in the same column as the pivot's diagonal to 0.
      ##Loop back
      
      archive_matrix = [] #saves the original form of the self.matrix
 
      for i in range(row):
        for j in range(column):
          if j == 0:
            archive_matrix.append([self.matrix[i][j]])
          else:
            archive_matrix[i].append(self.matrix[i][j])
 
      Matrix_Multiplier = 1 #will be multiplied to the determinants if a switch or rows/columns happened
      for i in range(row - 1):
        pivot = self.matrix[i]
        diagonal = self.matrix[i][i]
        if diagonal == 0:
          for j in range(i+1,row):
            candidate_row_element = self.matrix[j][i]
            if candidate_row_element != 0:
              candidate_row = self.Matrix[j]
              candidate = 'row'
              row_origin = j
              break
            elif j == max(range(row)):
              for j in range(i+1,column):
                candidate_column_element = self.matrix[i][j]
                if candidate_column_element != 0:
                  candidate_column = self.MatrixTranspose()[j]
                  candidate = 'column'
                  column_origin = j
                  break
                elif j == max(range(column)):
                  return 0
          if candidate == 'row':
            self.matrix[row_origin] = pivot
            pivot = candidate_row
            self.matrix[i] = pivot
            Matrix_Multiplier *= -1
          elif candidate == 'column':
            for element in range(len(pivot)):
              self.matrix[element][column_origin] = pivot[element]
            pivot = candidate_column
            for element in range(len(pivot)):
              self.matrix[element][i] = pivot[element]
            Matrix_Multiplier *= -1
        for i_next in range(i+1, row):
          reduct_row = self.matrix[i_next]
          reduct_row_diag_index = self.matrix[i_next][i]
          row_multiplier = - reduct_row_diag_index / diagonal
          result_reduct_row = []
          for j in range(len(reduct_row)):
            result_reduct_row.append(reduct_row[j] + row_multiplier * pivot[j])
          self.matrix[i_next] = result_reduct_row
 
      determinant = 1
      for i in range(row):
        determinant *= self.matrix[i][i]
      if determinant == 0:
        determinant = 0.0   
      else:
        determinant *= Matrix_Multiplier
      self.matrix = archive_matrix #return the original form of the matrix
    return determinant
  
  def M_cofactor(self):
    if self.row != self.column:
      raise ValueError("The matrix input is not a square matrix")
    #This will loop for all elements of the matrix
    ## First, get the cofactor of the element
    ## get the determinant of that cofactor
    ## if i + j is odd, multiply determinant by -1. Otherwise, do nothing
    ## create a new matrix for the original matrix's cofactor
    row, column = self.row, self.column
    result_matrix = []
    for i in range(row):
      for j in range(column):
        cofactor_matrix = []
        if (i + j) % 2 != 0:
          cofactor_multiplier = -1
        else:
          cofactor_multiplier = 1
        cofactor_row = 0
        for i_prime in range(row):
          cofactor_column = 0
          for j_prime in range(column):
            if not (i_prime == i or j_prime == j):
              if cofactor_column == 0:
                cofactor_matrix.append([self.matrix[i_prime][j_prime]])
              else:
                cofactor_matrix[cofactor_row].append(self.matrix[i_prime][j_prime])
              cofactor_column += 1
            if i != i_prime and j_prime == max(range(column)):
              cofactor_row += 1
        Mat_Obj_of_Cofactor = Matrix(cofactor_matrix)
        Cofactor_determinant = Mat_Obj_of_Cofactor.M_det()
        if j == 0: 
          result_matrix.append([round(cofactor_multiplier * Cofactor_determinant, 8)])
        else:
          result_matrix[i].append(round(cofactor_multiplier * Cofactor_determinant, 8))
    return result_matrix
 
  def M_inverse(self):
    if self.row != self.column:
      raise ValueError("The matrix input is not a square matrix")
    result_matrix = [] 
    cofactor = self.M_cofactor()
    determinant = self.M_det()
    for i in range(self.row):
      for j in range(self.column):
        if j == 0:
          result_matrix.append([round(cofactor[i][j] / determinant, 8)])
        else:
          result_matrix[i].append(round(cofactor[i][j] / determinant, 8))
    Mat_Obj_of_Result_Matrix = Matrix(result_matrix)
    return Mat_Obj_of_Result_Matrix.MatrixTranspose()

In [3]:
#Supporting functions to perform the output
 
def separator():
  print('-'.center(50,'-'))
 
def Rule1_dot(Matrix1, Matrix2, Matrix3):
  Result1 = Matrix1.Dot(Matrix2)
  MResult1 = Matrix(Result1)
  Result = MResult1.Dot(Matrix3)
  return Result
 
def matrix_cofactor(matrix):
  return np.linalg.inv(matrix).T * np.linalg.det(matrix)

In [5]:
#Initialization of Variables to be tested
 
A = [[1, 2, 3, 6], [7, 8, 9, 10], [11, 12, 13, 15]]
B = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
C = [[2, 3, 4], [5, 6, 7], [8, 9, 0]]
D = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]] 
E = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]] 
F = [[2, 4, 1], [5, -2, 2], [0, 1, 3]]
G = [[0, 1, 1, 1], [1, 1, 2, 2], [1, 0, 2, 1]]
H = [[4, 5, 7, - 2], [3, 5, 1, -0], [5, 9, -3, 5], [3, 5, 6, 2]] 
 
MatrixA = Matrix(A)
MatrixA_numpy = np.array(A)
MatrixB = Matrix(B)
MatrixB_numpy = np.array(B)
MatrixC = Matrix(C)
MatrixC_numpy = np.array(C)
MatrixD = Matrix(D)
MatrixD_numpy = np.array(D)
MatrixE = Matrix(E)
MatrixD_numpy = np.array(E)
MatrixF = Matrix(F)
MatrixF_numpy = np.array(F)
MatrixG = Matrix(G)
MatrixG_numpy = np.array(G)
MatrixH = Matrix(H)
MatrixH_numpy = np.array(H)

In [6]:
#Printing of output and comparison with numpy matrix operations to user-defined class "Matrix"
 
print(f'Matrix in Solution:\n{MatrixA.matrix}\nMatrix in numpy:\n{MatrixA_numpy}\n')
separator()
print(f'Matrix Transpose in Solution:\n{MatrixA.MatrixTranspose()}\nMatrix Transpose in numpy:\n{np.transpose(MatrixA_numpy)}\n')
separator()
print(f'Matrix Dot in Solution:\n{MatrixB.Dot(MatrixC)}\nMatrix Dot in numpy:\n{MatrixB_numpy @ MatrixC_numpy}\n')
separator()
print(f'Matrix Dot with non-square matrices in Solution:\n{MatrixF.Dot(MatrixG)}\n Matrix Dot with non-square matrices in numpy:\n{(MatrixF_numpy @ MatrixG_numpy)}\n')
separator()
#placeholder for rule 2
separator()
print(f'Matrix Determinant in Solution:\n{MatrixH.M_det()}\n Matrix Determinant in numpy:\n{np.linalg.det(MatrixH_numpy)}')
separator()
print(f'Matrix Cofactor in Solution:\n{MatrixF.M_cofactor()}\n Matrix Cofactor in numpy:\n{matrix_cofactor(MatrixF_numpy)}')
separator()
print(f'Matrix Inverse in Solution:\n{MatrixH.M_inverse()}\n Matrix Inverse in numpy:\n{np.linalg.inv(MatrixH_numpy)}')

Matrix in Solution:
[[1, 2, 3, 6], [7, 8, 9, 10], [11, 12, 13, 15]]
Matrix in numpy:
[[ 1  2  3  6]
 [ 7  8  9 10]
 [11 12 13 15]]

--------------------------------------------------
Matrix Transpose in Solution:
[[1, 7, 11], [2, 8, 12], [3, 9, 13], [6, 10, 15]]
Matrix Transpose in numpy:
[[ 1  7 11]
 [ 2  8 12]
 [ 3  9 13]
 [ 6 10 15]]

--------------------------------------------------
Matrix Dot in Solution:
[[36, 42, 18], [81, 96, 51], [126, 150, 84]]
Matrix Dot in numpy:
[[ 36  42  18]
 [ 81  96  51]
 [126 150  84]]

--------------------------------------------------
Matrix Dot with non-square matrices in Solution:
[[5, 6, 12, 11], [0, 3, 5, 3], [4, 1, 8, 5]]
 Matrix Dot with non-square matrices in numpy:
[[ 5  6 12 11]
 [ 0  3  5  3]
 [ 4  1  8  5]]

--------------------------------------------------
--------------------------------------------------
Matrix Determinant in Solution:
-128.99999999999997
 Matrix Determinant in numpy:
-128.99999999999997
-----------------------------