<a href="https://colab.research.google.com/github/diecilyngonzales/Lab-Activities-for-Linear-Algebra-58051/blob/main/Week%207/LinAlg_58051_Gonzales_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TASK 1

In [ ]:
 
import numpy as np
 
def mat_desc(matrix):           
    MShape = matrix.shape
    MSize = matrix.size
    MRank = matrix.ndim
    
    IsSquare = MShape[0] == MShape[1] 
 
    print(f'Matrix:\n{matrix}\n\nShape:\t{MShape}\nSize:\t{MSize}\nRank:\t{MRank}\n')
    print(f'Is Empty: {MSize == 0}\nIs Square: {IsSquare}\n') 
 
    IsIdentity = np.sum(np.identity(MShape[0]) == matrix) == MSize
    total = np.sum(matrix)
 
    IsOne = False
    IsZero = False
 
    if total == MSize:
        IsOne = True
    elif total == 0:
        IsZero = True         
 
    print(f'Is Identity: {IsIdentity}\nIs One Matrix: {IsOne}\nIs Zero Matrix: {IsZero}\n')  
 
A = np.array([[0, 3, 2, 4], [2, 0, 1, 4], [1, 3, 0, 3], [2, 4, 5, 1]])
B = np.array([[2, 9, 6],[0, 3, 5],[0, 0, 9], [2, 4, 6]])
C = np.array([[1, 0, 0, 0, 0],[0, 1, 0, 0, 0],[0, 0, 1, 0, 0],[0, 0, 0, 1, 0],[0, 0, 0, 0, 1]])
D = np.array([[0, 0, 0],[0, 0, 0],[0, 0, 0]])
E = np.array([[1, 1, 1, 1],[1, 1, 1, 1],[1, 1, 1, 1],[1, 1, 1, 1]])
 
matrices = [A, B, C, D, E]
 
for i in matrices:
    mat_desc(i)
    print('end of result'.center(40,'-'))

Matrix:
[[0 3 2 4]
 [2 0 1 4]
 [1 3 0 3]
 [2 4 5 1]]

Shape:	(4, 4)
Size:	16
Rank:	2

Is Empty: False
Is Square: True

Is Identity: False
Is One Matrix: False
Is Zero Matrix: False

-------------end of result--------------
Matrix:
[[2 9 6]
 [0 3 5]
 [0 0 9]
 [2 4 6]]

Shape:	(4, 3)
Size:	12
Rank:	2

Is Empty: False
Is Square: False

Is Identity: False
Is One Matrix: False
Is Zero Matrix: False

-------------end of result--------------
Matrix:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

Shape:	(5, 5)
Size:	25
Rank:	2

Is Empty: False
Is Square: True

Is Identity: True
Is One Matrix: False
Is Zero Matrix: False

-------------end of result--------------
Matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Shape:	(3, 3)
Size:	9
Rank:	2

Is Empty: False
Is Square: True

Is Identity: False
Is One Matrix: False
Is Zero Matrix: True

-------------end of result--------------
Matrix:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Shape:	(4, 4)
Size:	16
Rank:	2

Is Empty: False
Is Square: T

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


TASK 2

In [ ]:
 import numpy as np
 
class DimensionError(Exception):
    pass
 
def mat_desc(matrix):           
    MShape = matrix.shape
    MSize = matrix.size
    MRank = matrix.ndim
 
    IsSquare = MShape[0] == MShape[1]
 
    print(f'Matrix:\n{matrix}\n\nShape:\t{MShape}\nSize:\t{MSize}\nRank:\t{MRank}\n')
    print(f'Is Empty: {MSize == 0}\nIs Square: {IsSquare}\n')
 
    IsIdentity = np.sum(np.identity(MShape[0]) == matrix) == MSize
    total = np.sum(matrix)
 
    IsOne = False
    IsZero = False
 
    if total == MSize:
        IsOne = True
    elif total == 0:
        IsZero = True         
 
    print(f'Is Identity: {IsIdentity}\nIs One Matrix: {IsOne}\nIs Zero Matrix: {IsZero}\n')
 
def mat_operations(matrix1, matrix2):
    return_bool = False
    if not isinstance(matrix1, np.ndarray):
        print(f'{matrix1} is not a matrix.')
        return_bool = True
    if not isinstance(matrix2, np.ndarray):
        print(f'{matrix2} is not a matrix.') 
        return_bool = True
    if return_bool == True:
        return ''
 
    mat_desc(matrix1)
    print('end for Matrix 1'.center(40,'-'))
    mat_desc(matrix2)
    print('end for Matrix 2'.center(40,'-'))
 
    if matrix1.shape != matrix2.shape:
        raise DimensionError("The two matrices input have different dimensions")
 
    sum = matrix1 + matrix2
    diff = matrix1 - matrix2
    mult = matrix1 * matrix2
    divi = matrix1 / matrix2
 
    return [sum, diff, mult, divi]
 
A = np.array([[0, 3, 2, 4], [2, 0, 1, 4], [1, 3, 0, 3], [2, 4, 5, 1]])
B = np.array([[2, 9, 6],[0, 3, 5],[0, 0, 9], [2, 4, 6]])
C = np.array([[1, 0, 0, 0, 0],[0, 1, 0, 0, 0],[0, 0, 1, 0, 0],[0, 0, 0, 1, 0],[0, 0, 0, 0, 1]])
D = np.array([[0, 0, 0],[0, 0, 0],[0, 0, 0]])
E = np.array([[1, 1, 1, 1],[1, 1, 1, 1],[1, 1, 1, 1],[1, 1, 1, 1]])
 
print(mat_operations(A, E))

Matrix:
[[0 3 2 4]
 [2 0 1 4]
 [1 3 0 3]
 [2 4 5 1]]

Shape:	(4, 4)
Size:	16
Rank:	2

Is Empty: False
Is Square: True

Is Identity: False
Is One Matrix: False
Is Zero Matrix: False

------------end for Matrix 1------------
Matrix:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Shape:	(4, 4)
Size:	16
Rank:	2

Is Empty: False
Is Square: True

Is Identity: False
Is One Matrix: True
Is Zero Matrix: False

------------end for Matrix 2------------
[array([[1, 4, 3, 5],
       [3, 1, 2, 5],
       [2, 4, 1, 4],
       [3, 5, 6, 2]]), array([[-1,  2,  1,  3],
       [ 1, -1,  0,  3],
       [ 0,  2, -1,  2],
       [ 1,  3,  4,  0]]), array([[0, 3, 2, 4],
       [2, 0, 1, 4],
       [1, 3, 0, 3],
       [2, 4, 5, 1]]), array([[0., 3., 2., 4.],
       [2., 0., 1., 4.],
       [1., 3., 0., 3.],
       [2., 4., 5., 1.]])]
